### ISSUE TITLE
Trying to use it on Jenkis pipeline 

### ISSUE THREAD

**Issue by DanielGarciaGuillen** [pmadruga/react-native-clean-project#77]
First of all, thanks for this amazing package.

The amount of hours our team is saving is incredible thanks to your work.

I am working on our pipeline (Jenkins) and I would like to use the package to do the cleanup.

My apologies if the issue is actually not related to your package, but I am not sure why this is happening.

The issue I am facing is that it seems when I do npm run clean("clean": "react-native clean-project-auto" on package.json),
the step on Jenkins doesn't result in success.

Do you have any idea why? It should log it as a success and move on to the next steps, but that is not the case.

It stays there for as much time as I let it be, without returning a success.

Thanks in advance!

![Screen Shot 2021-08-30 at 5 39 45 PM](https://user-images.githubusercontent.com/17835646/131409280-0f1f452e-530d-4cca-a02c-97c5c43e0542.png)

**Comment by pmadruga** [comment]
Thank you for the kind words!

I believe it fails because `npm ci` considers a warning as a failure. Have you tried forking this package and adding `--loglevel=error`? More info [here](https://stackoverflow.com/questions/27686889/npm-install-warn-on-dependency). 

Otherwise, I can give a test drive during this week - I just need to find a case where I have warnings. If it solves, I'll push a fix right after.

**Comment by pmadruga** [comment]
Ok, so what I'll do is remove those messages. The "Error running" messages are more warnings than anything else. I'll bump a version this week.

**Comment by DanielGarciaGuillen** [comment]
I appreciate! Thanks man!
